version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/deploy/

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.bash
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.bash
      runas: root
