name: Apt-talk server deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Run test
        run: ./gradlew test

  deploy:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build docker image and push to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platform: linux/amd64
          push: true
          tags: ldntjd1081/apt-server:latest

      - name: Trigger the CodeDeploy in EC2 instance
        id: docker_build
        run: aws deploy create-deployment --region ap-northeast-2 --application-name apt-talk-code-deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name com.aptalk --github-location repository=wooseong-Lee/aptalk-server,commitId=${{ github.sha }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Print Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
