name: Apt-talk server deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@master

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Run test
        run: ./gradlew test

  deploy:
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - name: Build docker image and push to dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}
          repository: ldntjd1081/apt-server
          tags: latest

      - name: Trigger the CodeDeploy in EC2 instance
        run: aws deploy --region ap-northeast-2 create-deployment --application-name apt-talk-code-deploy --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name com.aptalk --github-location repository=wooseong-Lee/aptalk-server, commitId=${GITHUB_SHA}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          Default_region_name:
